builds:
- binary: "{{.ProjectName}}_v{{.Version}}"
  goos:
    - linux
    - windows
  goarch:
  - amd64
archives:
  - id: default
    format: zip
release:
  disable: true
blobs:
-
  provider: s3
  bucket: tfreg
  region: us-east-1
  folder: "ace/providers/{{.ProjectName}}/{{.Version}}"