builds:
- binary: terraform-provider-okta_v{{.Version}}
  goos:
    - linux
    - windows
  goarch:
  - amd64
archive:
  format: zip
s3:
-
  bucket: d2l-terraform-registry
  region: us-east-1
  folder: "providers/terraform-provider-okta/{{.Version}}"