builds:
- binary: "{{.Name}}_v{{.Version}}"
  goos:
    - linux
    - windows
  goarch:
  - amd64
archive:
  format: zip
release:
  disable: true
s3:
-
  bucket: tfreg
  region: us-east-1
  folder: "providers/{{.Name}}/{{.Version}}"