version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/Brightspace/terraform-provider-okta
    steps:
      - checkout
      - run:
          name: Dependencies
          command: go get -v -t -d
      - run:
          name: Build
          command: go build -v
      - run:
          name: Test
          command: go test -v -race
  package:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/Brightspace/terraform-provider-okta
    steps:
      - checkout
      - run:
          name: Install awscli
          command: apt update && apt install awscli
      - run:
          name: Dependencies
          command: go get -v -t -d
      - run:
          environment:
            GORELEASER_URL: "https://github.com/goreleaser/goreleaser/releases/download/v0.100.0/goreleaser_Linux_x86_64.tar.gz"
          name: Download goreleaser
          command: curl -L -s ${GORELEASER_URL} | sudo tar zxf - -C /usr/local/bin
      - run:
          name: Terraform Registry
          command: |
            export SESSION_NAME=circleci-${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BUILD_NUM}
            temp_role=$(aws sts assume-role --role-arn ${AWS_IAM_TFREG} --role-session-name ${SESSION_NAME})
            echo "export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)" >> $BASH_ENV
            echo "export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)" >> $BASH_ENV
      - run:
          name: Release
          command: /usr/local/bin/goreleaser

workflows:
  version: 2
  ci-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - package:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/